name: Build envoy for curiefense

# This build takes a long time, and exceeds the time limit for GitHub's default
# runner (>6 hours, with 2 CPUs)
# To run this, start the runner manually. It will power off automatically.
# gcloud compute instances start --zone=us-central1-a gh-runner-envoy
# (this could be automated later...)
# NEVER enable the custom runner on PRs
on:
  push:

jobs:
  build-envoy-for-curiefense:
    runs-on: self-hosted

    steps:
      - name: fix permissions
        # one command is run inside a container as "root", others as a non-root user... clean-up files ownership first.
        run: |
          sudo chown -R $(id -u) .
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build envoy binary for istio with exposed symbols
        run: |
          sed -i -e '/action_env=BAZEL_LINKOPTS=-lm$/s/$/:-Wl,-E/' envoy.bazelrc
          mkdir -p cf-out
          chmod 755 cf-out/
          # docker image is mentioned in https://github.com/istio/test-infra/blob/master/prow/config/jobs/proxy-1.9.yaml
          docker run --rm -v /cache/istio-home:/home/.cache -v /cache/istio-root:/root/.cache -v $(realpath .):/work envoyproxy/envoy-build-ubuntu:11efa5680d987fff33fde4af3cc5ece105015d04 /work/build-cf-envoy.sh
          sudo chown -R $(id -u) .
          sudo chown $(id -u) cf-out/envoy
          chmod 755 cf-out/envoy
          echo -en 'FROM scratch\nCOPY envoy /envoy' > cf-out/Dockerfile
          strip cf-out/envoy
          objdump -T cf-out/envoy |grep lua_checkstack
          cd cf-out
          docker build -t curiefense/envoy-istio-cf:$GITHUB_SHA .
      - name: Push the image
        run: |
          docker login -u "${{ secrets.DOCKER_HUB_USER }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker images
          docker push curiefense/envoy-istio-cf:$GITHUB_SHA
